version: '3'

services:
  api:
    image: api
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - 8000:8000
      - 5678:5678
    command: sh -c "python manage.py makemigrations && pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
    volumes:
      - ./:/app/
    networks:
      - couple-backend
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: couple
    volumes: 
      - couple-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: couple
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: "12345"
      MYSQL_ROOT_PASSWORD: "12345"
    ports:
      - 3307:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - couple-backend

  redis:
    image: redis:5.0-alpine
    ports: 
      - 6379:6379
    restart: unless-stopped
    volumes: 
      - couple-redis:/data
  
  worker:
    build:
      context: .
      dockerfile: Dockerfile.debug
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - couple:/app/ # shared volume between worker and api for media
    networks:
      - couple-backend

volumes:
  couple:
  couple-data:
  couple-redis:

networks:
  couple-backend:
    driver: bridge