version: '3'

services:
  api:
    image: api
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
    volumes:
      - ./:/app/
    links:
      - redis
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7
    container_name: couple-data
    volumes: 
      - couple-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: couple
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: "12345"
      MYSQL_ROOT_PASSWORD: "12345"
    ports:
      - 3307:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:5.0-alpine
    container_name: redis_server
    ports: 
      - 6379:6379
    restart: unless-stopped
    volumes: 
      - couple-redis:/data
  
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: celery -A api worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - ./:/app/ 

volumes:
  couple:
  couple-data:
  couple-redis: